### ISSUE TITLE
Shader::setslotparam related texture switching crash

### ISSUE THREAD

**Issue by no-lex** [project-imprimis/libprimis#183]
Upon switching to some of the windows textures, the game segfaults.

```
Shader::setslotparams (this=0x55555615dc78, slot=..., vslot=...) at engine/render/shader.cpp:699
699	        SETSLOTPARAMS(slot.params)
#0  Shader::setslotparams (this=0x55555615dc78, slot=..., vslot=...) at engine/render/shader.cpp:699
        p = <optimized out>
        l = <optimized out>
        i = 1
        unimask = 2147483648
#1  0x00007ffff7a03492 in Shader::set (vslot=..., slot=..., this=<optimized out>)
    at engine/render/texture.h:426
        vslot = <optimized out>
        slot = <optimized out>
        this = <optimized out>
#2  changeshader (cur=..., cur=..., b=..., b=..., pass=4) at engine/render/renderva.cpp:1982
        vslot = <optimized out>
        slot = @0x555556da8cf0: {_vptr.Slot = 0x7ffff7cdc978 <vtable for Slot+16>, index = 14, smooth = -1, 
          sts = {static MINSIZE = 8, buf = 0x555556d9fc50, alen = 8, ulen = 3}, shader = 0x555555a86f00, 
          params = {static MINSIZE = 8, buf = 0x555556da16b0, alen = 8, ulen = 2}, 
          variants = 0x555556bae500, loaded = true, texmask = 11, grass = 0x0, grasstex = 0x0, 
          thumbnail = 0x555557b0b740}
        vslot = <optimized out>
        slot = <optimized out>
#3  renderbatches (cur=..., pass=pass@entry=4) at engine/render/renderva.cpp:2071
        b = <optimized out>
        curbatch = -1
#4  0x00007ffff7a08eb2 in renderrsmgeom (dyntex=<optimized out>) at engine/render/renderva.cpp:2511
        cur = {colormask = true, depthmask = true, alphaing = 0, vbuf = 49, vattribs = true, 
          vquery = false, colorscale = {{{x = 1, y = 1, z = 1}, {r = 1, g = 1, b = 1}, v = {1, 1, 1}}}, 
          alphascale = 0, refractscale = 0, refractcolor = {{{x = 1, y = 1, z = 1}, {r = 1, g = 1, b = 1}, 
              v = {1, 1, 1}}}, globals = 58031, tmu = 0, textures = {142, 143, 0, 0, 0, 0, 0}, 
          slot = 0x555556da8cf0, texgenslot = 0x555556bace30, vslot = 0x555556bae500, 
          texgenvslot = 0x55555645ff00, texgenscroll = {{{x = 0, y = 0}, v = {0, 0}}}, texgenorient = 6, 
          texgenmillis = 0}
#5  0x00007ffff79a49aa in renderradiancehints () at engine/render/radiancehints.cpp:903
        rhcputimer = 0x0
        rhtimer = 0x0
#6  0x00007ffff79c4e75 in workinoq () at engine/render/renderlights.cpp:3776
No locals.
#7  0x00007ffff7a08921 in rendergeom () at engine/render/renderva.cpp:2341
        doOQ = <optimized out>
        multipassing = false
        cur = {colormask = false, depthmask = false, alphaing = 0, vbuf = 0, vattribs = false, 
          vquery = false, colorscale = {{{x = 1, y = 1, z = 1}, {r = 1, g = 1, b = 1}, v = {1, 1, 1}}}, 
          alphascale = 0, refractscale = 0, refractcolor = {{{x = 1, y = 1, z = 1}, {r = 1, g = 1, b = 1}, 
              v = {1, 1, 1}}}, globals = -1, tmu = -1, textures = {0, 0, 0, 0, 0, 0, 0}, slot = 0x0, 
          texgenslot = 0x0, vslot = 0x0, texgenvslot = 0x0, texgenscroll = {{{x = 0, y = 0}, v = {0, 0}}}, 
          texgenorient = -1, texgenmillis = 9484}
#8  0x00007ffff79bb0a0 in rendergbuffer (depthclear=depthclear@entry=true, 
    gamefxn=gamefxn@entry=0x5555555a2640 <game::rendergame()>) at engine/render/renderlights.cpp:4248
        gcputimer = <optimized out>
        gtimer = 0x0
#9  0x00007ffff79af090 in gl_drawview (gamefxn=gamefxn@entry=0x5555555a2640 <game::rendergame()>, 
    hudfxn=hudfxn@entry=0x5555555a4530 <game::renderavatar()>) at engine/render/rendergl.cpp:1985
        scalefbo = 4
        fogmargin = <optimized out>
        fogmat = 0
        abovemat = 0
        fogbelow = 0
#10 0x00007ffff79b0498 in gl_drawframe (crosshairindex=0, gamefxn=0x5555555a2640 <game::rendergame()>, 
    hudfxn=0x5555555a4530 <game::renderavatar()>) at engine/render/rendergl.cpp:2116
No locals.
#11 0x0000555555560f60 in main (argc=<optimized out>, argv=<optimized out>) at game/main.cpp:308
        frames = 860
        millis = 9484
        crosshairindex = <optimized out>
        timeerr = 0
        scaledtime = <optimized out>
        gamefxn = <optimized out>
        hudfxn = <optimized out>
```

**Comment by no-lex** [comment]
Not caused by 1e0a3a5c39690c422cd77f8f81faa70101fd7727
